### ISSUE TITLE
AsciiDoctor Support

### ISSUE THREAD

**Issue by sirinath** [softcover/softcover#134]
http://asciidoctor.org/

**Comment by atsaloli** [comment]
I have materials in AsciiDoc format.  I'd love to be able to feed SoftCover my AsciiDoc sources.  Otherwise I plan to convert them to DocBook, and then from DocBook to Markdown, to get them into SoftCover.  (Or else rewrite them in Markdown if the conversion gets ugly.)  I realize adding AsciiDoc support may not be a light request. =)

**Comment by sirinath** [comment]
Ascii Doc is becoming more popular hence it is good to support Gitbook supports it.

**Comment by nicolaiparlog** [comment]
I'm dabbling with writing and am currently researching a tool chain (who said procrastination?). As soon as I heard about Softcover I wanted to use it and looking at the docs only reinforced that snap judgement - it looks really great! In a similar fashion, I came to the conclusion that I should use Asciidoctor.

This lead me here... :wink:

**Comment by nicolaiparlog** [comment]
I guess this means no Asciidoc support in Softcover?

**Comment by mhartl** [comment]
Right, there are no plans to support AsciiDoc at this time.
