### ISSUE TITLE
Lack of XML quoting of chapter titles when generating epub results in invalid XML

### ISSUE THREAD

**Issue by itamarst** [softcover/softcover#188]
If a chapter title contains e.g. `&`, the resulting XML in `toc.ncx` is invalid since the ampersand doesn't get the appropriate entity. 

If a chapter starts with:

```markdown
# Things & Other Things
```

the generated XML looks like this:

```xml
<navPoint id="things" playOrder="9">
    <navLabel><text>Chapter 10: Things & Other Things
</text></navLabel>
```

That should be `&amp;` I think, or whatever the XML entity is (notice GitHub's angry "this is invalid" highlighting).

**Comment by mhartl** [comment]
Ampersands are a mess in both HTML and LaTeX. I regret using one in the title of *Learn Enough CSS & Layout*. Rather than go down a potential rabbit hole to fix it in all possible cases, though, I think at this point I’ll just recommend using “and” instead. (An imperfect solution, to be sure, but this just isn’t a high priority right now.)
