### ISSUE TITLE
Docker book template build throws warning and failure messaages

### ISSUE THREAD

**Issue by jcandan** [softcover/softcover#228]
### Problem

A new build from the Docker container displays LaTeX requested package, LaTeX Font shape undefined, hyperref already been used,  Referenced file not found, and Failed to find image messages and warnings.

### Steps to reproduce

SSH into the container, and run:

```
softcover new ExampleBook
cd ExampleBook
softcover build
```

### Expected behavior

Being a docker container, I would imagine no errors or warnings of missing things should be thrown.

**Comment by mhartl** [comment]
This appears to be system-dependent, as I am unable to reproduce on macOS. When you say “**the** Docker container”, what are you referring to? There is no official Softcover Docker container as far as I know.

In any case, warning messages (as opposed to outright errors) are probably safe to ignore.

**Comment by jcandan** [comment]
There's a softcover owned repo and dockerhub image at https://hub.docker.com/r/softcover/softcover. 😄

**Comment by mhartl** [comment]
It looks like my cofounder set that up at some point, a possibility I anticipated (thus the caveat “as far as I know”). You’ll note that it’s linked neither from the softcover.io website nor from the [manual](https://manual.softcover.io/book), so it’s not officially supported.

You’re still welcome to use it, but if you’d like to raise issues related to it then I suggest using the [softcover-docker](https://github.com/softcover/softcover-docker) repo rather than this one.
